---
controller_credentials:
  - name: "Demo Credential"
    credential_type: Machine
    state: absent

  - name: GitHub Access Token - aludwar
    organization: HomeLab
    credential_type: Source Control
    inputs:
      username: aludwar
      password: "{{ aludwar_github_token }}"

  - name: GitLab Access Token - aludwar
    organization: HomeLab
    credential_type: Source Control
    inputs:
      username: aludwar
      password: "{{ aludwar_gitlab_token }}"
      
  - name: SSH - aludwar
    organization: "HomeLab"
    credential_type: "Machine"
    inputs:
      username: "aludwar"
      password: "{{ aludwar_machine_password }}"
      ssh_key_data: "{{ aludwar_ssh_private_key }}"
