---
- name: Access Addition - User on-boarding
  hosts: dc01
  gather_facts: false

  tasks:
    - name: Active Directory - Add User
      microsoft.ad.user:
        name: "{{ firstname }} {{ surname }}"
        firstname: "{{ firstname }}"
        surname: "{{ surname }}"
        sam_account_name: "{{ firstname[0] }}{{ surname }}"
        company: BobCo
        password: "{{ temp_password }}"
        state: present
        street: "{{ street }}"
        city: "{{ city }}"
        state_province: IN
        postal_code: "{{ postal_code }}"
        country: US
        attributes:
          telephoneNumber: "{{ telephone_number }}"
      register: new_user

    - name: Display User
      ansible.builtin.debug:
        var: new_user

    - name: Show temp password
      ansible.builtin.debug:
        var: temp_password
