---
- name: Verify DNS functionality AND/OR refresh DNS cache
  hosts: dns.ludwar.ca
  gather_facts: false
  become: true

  tasks:
    - name: Verify DNS services using local scripts
      ansible.builtin.command:
        cmd: "/usr/local/bin/{{ item }}"
      loop:
        - dns_resolve_test.sh
        - refresh_populate_dns_cache_pihole.sh
        - refresh_populate_dns_cache.sh
      register: service_verification
      changed_when: false
