---
- name: Gather Facts and Output Host Variables
  hosts: all
  gather_facts: yes

  tasks:
    - name: Create host variables text file
      ansible.builtin.template:
        src: host_variables.j2
        dest: /home/aludwar/host_variables.txt
      delegate_to: nfs.ludwar.ca
