---
- name: Capture Connectivity Metrics for Linux and Windows Servers
  hosts: all
  gather_facts: yes

  tasks:
    - name: Ping Linux Servers
      ansible.builtin.ping:
      register: ping_result
      when: "'Linux' in ansible_facts['ansible_distribution']"

    - name: Display Ping Results for Linux Servers
      ansible.builtin.debug:
        var: "{{ item.ansible_facts['ansible_fqdn'] }} + ': ' + {{ item.ping }}"
      loop: "{{ ansible_play_hosts | map('extract', hostvars) | selectattr('ansible_facts.ansible_distribution', 'equalto', 'Linux') | list }}"
      when: item.ping is defined

#    - name: Ping Windows Servers
#      ansible.windows.win_ping:
#      register: ping_result
#      when: "'Windows' in ansible_facts['ansible_distribution']"
#
#    - name: Display Ping Results for Windows Servers
#      ansible.builtin.debug:
#        var: item.ansible_facts['ansible_fqdn'] + ": " + item.ping
#      loop: "{{ ansible_play_hosts | map('extract', hostvars) | selectattr('ansible_facts.ansible_distribution', 'equalto', 'Windows') | list }}"
#      when: item.ping is defined

    - name: Calculate Reachability Percentage
      set_fact:
        reachable: "{{ ping_result.results | selectattr('ping', 'defined') | list | length }}"
        total_servers: "{{ ansible_play_hosts | length }}"

    - name: Write Ping Results to File
      ansible.builtin.template:
        src: metric_connectivity.j2
        dest: /home/aludwar/metric_connectivity_report.txt
      delegate_to: nfs.ludwar.ca

