---
- name: Capture Connectivity Metrics for Linux and Windows Servers
  hosts: all
  gather_facts: true

  tasks:
    - name: Ping Linux Servers
      ansible.builtin.ping:
      register: ping_result
      when: ansible_facts['distribution'] == "RedHat"

    - name: Calculate Reachability Percentage
      ansible.builtin.set_fact:
        reachable: "{{ ansible_play_hosts | length }}"
        total_servers: "{{ ansible_play_hosts_all | length }}"

    - name: Display Reachability Percentage
      ansible.builtin.debug:
        msg: "{{ reachable }} reachable out of {{ total_servers }}"

    - name: Write Ping Results to File
      ansible.builtin.template:
        src: metric_connectivity.j2
        dest: /home/aludwar/metric_connectivity_report.txt
        mode: "0644"
      delegate_to: nfs.ludwar.ca
