---
- name: Activate Red Hat Insights on RHEL clients
  hosts: all
  become: yes
  collections:
    - redhat.insights
  vars:
    redhat_portal_username: "{{ rhnusername }}"
    redhat_portal_password: "{{ rhnpassword }}"

  tasks:
    - include_role:
        name: redhat.insights.insights_client
      when: ansible_os_family == 'RedHat'
