---
# This playbook updates all RHEL hosts
- hosts: all
  vars: 

  tasks:
    - name: Ensure the latest patches and errata are applied to linux clients
      yum:
        name: '*'
        state: latest
