---
# This playbook updates all RHEL hosts
- name: Update all packages on every host to the latest
  hosts: all
  
  tasks:
    - name: Ensure the latest patches and errata are applied to linux clients
      ansible.builtin.dnf:
        name: '*'
        state: latest
        