---
- name: Backup Mikrotik RouterOS Configuration
  hosts: routeros
  remote_user: aludwar
  tasks:
    - name: Collect all facts from devices
      community.routeros.facts:

    - name: Backup device to local device storage
      community.routeros.command:
        commands: '/system backup save name="{{ ansible_facts.date_time.date }}.{{ ansible_net_hostname }}" dont-encrypt=yes'

    - name: Copy backup file to local workstation
      ansible.builtin.command: "sftp aludwar@{{ ansible_net_hostname }}:{{ ansible_facts.date_time.date }}.{{ ansible_net_hostname }}.backup /home/aludwar/Documents/al_consulting/HomeNetwork/"
      delegate_to: 10.0.0.4
