rhel8_repo_list:
  - name: "Red Hat Enterprise Linux 8 for x86_64 - AppStream RPMs 8"
    product: "Red Hat Enterprise Linux for x86_64"
  - name: "Red Hat Enterprise Linux 8 for x86_64 - BaseOS RPMs 8"
    product: "Red Hat Enterprise Linux for x86_64"
  - name: "Red Hat Satellite Client 6 for RHEL 8 x86_64 RPMs"
    product: "Red Hat Enterprise Linux for x86_64"

rhel9_repo_list:
  - name: "Red Hat Enterprise Linux 9 for x86_64 - AppStream RPMs 9"
    product: "Red Hat Enterprise Linux for x86_64"
  - name: "Red Hat Enterprise Linux 9 for x86_64 - BaseOS RPMs 9"
    product: "Red Hat Enterprise Linux for x86_64"
  - name: "Red Hat Satellite Client 6 for RHEL 9 x86_64 RPMs"
    product: "Red Hat Enterprise Linux for x86_64"

aap_repo_list:    
  - name: "Red Hat Ansible Automation Platform 2.4 for RHEL 9 x86_64 RPMs"
    product: "Red Hat Ansible Automation Platform"
