---
# This playbook publishes new content versions in preparation for 
# promoting these content views through lifecycle environments
- hosts: satellite.ludwar.ca
  vars: 
    validate_certs: false

  tasks:
    - name: "Publish new content view versions for all configured Content Views"
      redhat.satellite.content_view_version:
        username: "{{ satellite_username }}"
        password: "{{ satellite_password }}"
        server_url: "{{ satellite_server_url }}"
        organization: "{{ satellite_organization }}"
        description: "Auto-publish new version pushed via Ansible"
        content_view: "{{ item.name }}"
      loop: "{{ content_views }}"
