---
- name: Configure Ansible Automation Platform
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Load all configuration files
      ansible.builtin.include_vars:
        dir: configs
        extensions:
          - yml
      tags:
        - always

    - name: Configure AAP using dispatch role
      ansible.builtin.include_role:
        name: infra.aap_configuration.dispatch
