---
- name: Capture Connectivity Metrics for Secure Servers
  hosts: secure_servers
  gather_facts: false

  tasks:
    - name: Ping Secure Servers
      ansible.builtin.ping:
      register: ping_result
      when: ansible_facts['distribution'] == "RedHat"

    - name: Calculate Reachability Percentage
      ansible.builtin.set_fact:
        reachable: "{{ ansible_play_hosts | length }}"
        total_servers: "{{ ansible_play_hosts_all | length }}"

- name: Write Connectivity Results to File
  hosts: nfs.ludwar.ca
  gather_facts: false
  remote_user: aludwar
  
  tasks:
    - name: Populate results into connectivity report
      ansible.builtin.template:
        src: connectivity.j2
        dest: /home/aludwar/connectivity_report.txt
        mode: "0644"
      delegate_to: nfs.ludwar.ca
