---
- name: Capture Connectivity Metrics for Secure Servers
  hosts: secure_servers
  gather_facts: false

  tasks:
    - name: Ping Secure Servers
      ansible.builtin.ping:
      register: ping_result

    - name: Calculate Reachability Percentage
      ansible.builtin.set_fact:
        cacheable: true
        reachable: "{{ ansible_play_hosts | length }}"
        total_servers: "{{ ansible_play_hosts_all | length }}"

- name: Write Connectivity Results to File
  hosts: nfs.ludwar.ca
  gather_facts: false
  remote_user: aludwar
  
  tasks:
#    - name: Populate results into connectivity report
#      ansible.builtin.template:
#        src: connectivityi_s.j2
#        dest: /home/aludwar/connectivity_report.txt
#        mode: "0644"
#      delegate_to: nfs.ludwar.ca

    - name: Append results to connectivity report
      ansible.builtin.blockinfile:
        dest: /home/aludwar/connectivity_report.txt
        block: "{{ lookup('template', 'connectivity_s.j2') }}"
        marker: ""
      delegate_to: nfs.ludwar.ca
