---
- name: Capture Connectivity Metrics for Windows Servers
  hosts: win1.dev.ludwar.ca
  gather_facts: true
  vars:
    ansible_user: ansible
    ansible_password: Windows00
    ansible_connection: winrm
    ansible_port: 5985
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore

  tasks:
    - name: Ping Windows Servers
      ansible.windows.win_ping:
      register: ping_result
        #      when: ansible_facts['distribution'] == "RedHat"

    - name: Calculate Reachability Percentage
      ansible.builtin.set_fact:
        reachable: "{{ ansible_play_hosts | length }}"
        total_servers: "{{ ansible_play_hosts_all | length }}"

- name: Write Connectivity Resutls to File
  hosts: nfs.ludwar.ca

  tasks:
    - name: Write Connectivity Results to File
      ansible.builtin.template:
        src: connectivity.j2
        dest: /home/aludwar/metric_connectivity_report.txt
        mode: "0644"
