---
- name: Capture Connectivity Metrics for Windows Servers
  hosts: 10.0.0.227
  gather_facts: true

  tasks:
    - name: Ping Windows Servers
      ansible.wndows.win_ping:
      register: ping_result
        #      when: ansible_facts['distribution'] == "RedHat"

    - name: Calculate Reachability Percentage
      ansible.builtin.set_fact:
        reachable: "{{ ansible_play_hosts | length }}"
        total_servers: "{{ ansible_play_hosts_all | length }}"

    - name: Write Connectivity Results to File
      ansible.builtin.template:
        src: metric_connectivity.j2
        dest: /home/aludwar/metric_connectivity_report.txt
        mode: "0644"
      delegate_to: nfs.ludwar.ca
