---
- name: Capture Connectivity Metrics for Linux Servers
  hosts: all
  gather_facts: true

  tasks:
    - name: Ping Red Hat Enterprise Linux Servers
      ansible.builtin.ping:
      register: ping_result
      when: ansible_facts['distribution'] == "RedHat"

    - name: Calculate Reachability Percentage
      ansible.builtin.set_fact:
        reachable: "{{ ansible_play_hosts | length }}"
        total_servers: "{{ ansible_play_hosts_all | length }}"

- name: Write Connectivity Results to File
  hosts: nfs.ludwar.ca
  
  tasks:
    - name: Write Connectivity Results to File
      ansible.builtin.template:
        src: connectivity.j2
        dest: /home/aludwar/metric_connectivity_report.txt
        mode: "0644"
      delegate_to: nfs.ludwar.ca
