---
- name: Capture Connectivity Metrics for Windows Servers
  hosts: windows_servers
  gather_facts: false
  vars:
    ansible_user: ansible
    ansible_password: Windows00
    ansible_connection: winrm
    ansible_port: 5985
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore

  tasks:
    - name: Ping Windows Servers
      ansible.windows.win_ping:
      register: ping_result

    - name: Calculate Reachability Percentage
      ansible.builtin.set_fact:
        cacheable: true
        reachable: "{{ ansible_play_hosts | length }}"
        total_servers: "{{ ansible_play_hosts_all | length }}"

- name: Write Connectivity Results to File
  hosts: nfs.ludwar.ca
  gather_facts: false

    - name: Populate results to connectivity report
      ansible.builtin.template:
        src: connectivity.j2
        dest: /home/aludwar/connectivity_report.txt
        mode: "0644"
